'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Ransomware.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_hIhIxbWsV_0si0iiLRgubQ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1_hIhIxbWsV-0si0iiLRgubQ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_hIhIxbWsV_0si0iiLRgubQ1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1_hIhIxbWsV-0si0iiLRgubQ1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8ebe18400524d0d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8ebe18400524d0d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bitcoin_accepted_here___gold_big_1680px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bitcoin-accepted-here_-_gold-big-1680px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BTC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BTC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BTC1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BTC1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BTC2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BTC2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gesloten_slot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gesloten_slot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Giphy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Giphy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Giphy_Galaxy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Giphy Galaxy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Giphy1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Giphy1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Giphy2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Giphy2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Giphy3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Giphy3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_Lock_red_1891028() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_Lock_red_1891028", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_payment_method_bitcoin_206681() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_payment_method_bitcoin_206681", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_payment_method_bitcoin_2066811() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_payment_method_bitcoin_2066811", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_payment_method_bitcoin_2066812() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_payment_method_bitcoin_2066812", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ignited_Chica_office_jumpscare_42042() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ignited_Chica_office_jumpscare_42042", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ignited_Chica_office_jumpscare_420421() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ignited_Chica_office_jumpscare_420421", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property memeyaoming1024() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("memeyaoming1024", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property O() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("O", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property personal_trollface_hd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("personal_trollface_hd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tingkat_level() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tingkat level", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WannaCry_ransom_note__Please_Read_Me__txt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WannaCry-ransom-note-@Please_Read_Me@-txt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WannaCry_ransom_note__Please_Read_Me__txt1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WannaCry-ransom-note-@Please_Read_Me@-txt1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property yao_ming_meme_new_version_hd_by_guillersevilla_d3dwein() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yao_ming_meme_new_version_hd_by_guillersevilla-d3dwein", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
